version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"

conda:
  environment: environments.yml

sphinx:
  builder: html
  configuration: docs/source/conf.py

formats:
  - pdf
  - epub