name: mol_translator
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - openbabel=3.1.1
  - pytest
  - tqdm
  - mypy
  - ipykernel
  - cython
  - numba
  - autopep8
  - pip-tools
  - pip:
    - sphinx==4.5.0
    - myst-parser==0.17.2
    - sphinx-rtd-theme==1.0.0